site_name: django_crispy_idempotency
site_description: Django Rest API idempotency at granuler(API level) and application level
repo_url: https://github.com/covergenius/django-crispy-idempotency
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/covergenius">covergenius</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
